export enum CommonCode {
    
    // mentee token names
    MENTEE_ACCESS_TOKEN = 'MENTEE_ACCESS_TOKEN',
    MENTEE_REFRESH_TOKEN = 'MENTEE_REFRESH_TOKEN',

    //mentor token names
    MENTOR_ACCESS_TOKEN = 'MENTOR_ACCESS_TOKEN',
    MENTOR_REFRESH_TOKEN = 'MENTOR_REFRESH_TOKEN',

    //admin token names
    ADMIN_ACCESS_TOKEN = 'ADMIN_ACCESS_TOKEN',
    ADMIN_REFRESH_TOKEN = 'ADMIN_REFRESH_TOKEN',
}